name: Code formatting check

on:
  pull_request:

# Cancel previous runs if a more recent commit is pushed.
concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}
  cancel-in-progress: true

permissions: read-all

jobs:
  clang-format-check:
    name: clang-format
    runs-on: "ubuntu-20.04"
    steps:
      - name: Setup clang-format
        run: |
          sudo apt-get install -yqq clang-format-16
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: '0'
      - name: Switch to pull request branch
        run: |
          git checkout ${GITHUB_SHA}
      - name: Check formatting
        uses: DoozyX/clang-format-lint-action@v0.17
        with:
          source: '.'
          exclude: './third_party'
          clangFormatVersion: 16
          style: 'file:.clang-format'
